# Generated by Django 4.0.1 on 2022-01-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
