# Generated by Django 4.0.1 on 2022-01-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('audio', models.CharField(max_length=200)),
                ('bookmark', models.IntegerField()),
                ('liked_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to='user.user')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
