# Generated by Django 4.0.1 on 2022-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_created_at_alter_book_liked_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
