# Generated by Django 4.0.1 on 2022-04-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
