# Generated by Django 4.0.1 on 2022-04-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
